apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
    type: hello-world-app 
spec:
  replicas: 1  
  selector:
    matchLabels:
      type: hello-world-app  
  template:
    metadata:
      name: my-app-pod
      labels:
        app: my-app
        type: hello-world-app 
    spec:
      containers:
      - name: my-app-container
        image:533267424796.dkr.ecr.ap-southeast-1.amazonaws.com/demo:p5